### ISSUE TITLE
? Empty Repo?

### ISSUE THREAD

**Issue by winkler1** [Brainfock/Brainfock#2]
Hi,
 I'm confused - the ReadMe says to follow Setup.md, but there's no such file and the whole repo is two .MD files.... ???
##

**Comment by Webkadabra** [comment]
@winkler1 Hey, sorry I didn't saw your message earlier. Brainfock haven't been released to the public yet, please, follow for updates — I'm working hard ot release it ASAP. Thanks!

**Comment by zanjs** [comment]
how nice! Code which went?

**Comment by amstr1k** [comment]
Когда код то будет?

**Comment by Webkadabra** [comment]
@amstr1k @zanjs and everybody who has already made me happy by starring this repo, I'm writing to let you know project is ALIVE. Hopefully I will be able to release it in coming weeks — I feel obligated to bring the best thing I can at the moment and in a timeframe I have. Please, support me with a tweet or FB post to this repo or Brainfock.org website.

Thanks a lot! Please, stay tuned!

**Comment by Webkadabra** [comment]
@amstr1k @ondrejbartas @winkler1 @zanjs @XeeD I'm very happy (and scared a lot) to let you guys know that Brianfock code is now available. Please, let someone know about this who You think might help us. Thanks!
