### ISSUE TITLE
Goals

### ISSUE THREAD

**Issue by dv336699** [Brainfock/Brainfock#3]
Something it would be real nice to have
http://latticehq.com/

**Comment by Webkadabra** [comment]
@diego-vieira thanks for the suggestion about goals! Actually, I look at any task/ticket/topic as a "goal to complete" (fix bug, solve question, release version), and I'm trying to build initial brainfock release with that notion in mind. 

All "topics" in system (e.g. projects: http://brainfock.org/projects?groupBy=workspace or issues of a project: http://brainfock.org/brainfock/BFC/issues) are treated as what you might call - "goals".

Based on topic/project settings (project is really just a parent topic), topics have their stages, workflows and operaitons (e.g. "Begin progress" on a task (implemented, see demo), or possible "Mark quesiton as solved" or "Release version" on a "version" or "milestone"-type topic.

As you can see, there's a lot to be covered in documentation, so I hope releasing Brainfock code will help with that, not make things more confusing :)
